#!/bin/bash

############################################################################
# Copyright (c) 2011-2014 Saint-Petersburg Academic University
# All Rights Reserved
# See file LICENSE for details.
############################################################################

cmd=cp
if [ $# = 0 ]
    then
        set 1 '-all'
fi

for arg; do
    if [ $arg = '-d' ]
        then
            cmd=diff
            if [ $# = 1 ]; then
                set 1 '-all' 
            fi
    fi
done

for arg; do

case $arg in
  'ig') $cmd configs/ig_repertoire_constructor/config.info.template configs/ig_repertoire_constructor/config.info;;
  'logig') $cmd configs/ig_repertoire_constructor/log.properties.template configs/ig_repertoire_constructor/log.properties;;
  '-all')
		echo -----------configs/ig_repertoire_constructor/config.info--------
		$cmd configs/ig_repertoire_constructor/config.info.template configs/ig_repertoire_constructor/config.info
		echo ----------configs/ig_repertoire_constructor/log.properties------
		$cmd configs/ig_repertoire_constructor/log.properties.template configs/ig_repertoire_constructor/log.properties 
esac

done
