blank <- read.table(file = "v_blank.txt")
blank_wo_alleles <- read.table(file = "v_blank_wo_alleles.txt")
germline_normal <- read.table('v_germlines_normal.txt')
germline_normal_wo_alleles <- read.table('v_germlines_normal_wo_alleles.txt')
germline_pseudo <- read.table('v_germlines_pseudo.txt')
germline <- union(unlist(germline_pseudo), unlist(germline_normal))
blank <- unlist(blank)
germline <- unlist(germline)
t(t(setdiff(blank, germline)))

blank <- read.table(file = "d_blank.txt")
germline_normal <- read.table('d_germlines_normal.txt')
germline_pseudo <- read.table('d_germlines_pseudo.txt')
germline <- union(unlist(germline_pseudo), unlist(germline_normal))
blank <- unlist(blank)
germline <- unlist(germline)
t(t(setdiff(blank, germline)))

blank <- read.table(file = "j_blank.txt")
germline_normal <- read.table('j_germlines_normal.txt')
germline_pseudo <- read.table('j_germlines_pseudo.txt')
germline <- union(unlist(germline_pseudo), unlist(germline_normal))
blank <- unlist(blank)
germline <- unlist(germline)
t(t(setdiff(blank, germline)))
