include ../Makefile_vars

DENSE_SUBGRAPH_FINDER_PATH = ../dense_subgraph_finder

all:
	$(MAKE) -C $(DENSE_SUBGRAPH_FINDER_PATH)
	$(MAKE) uncompressed.fa

uncompressed.fa: $(BIN)/ig_consensus_finder $(DENSE_SUBGRAPH_FINDER_PATH)/$(DENSE_SUBGRAPHS)
	python $(PY_SRC)/rcm_recoverer.py \
	--ids-file ../umi_clustering/$(INTER_REP) \


 	$(BIN)/ig_consensus_finder \
 	--input-file $(DENSE_SUBGRAPH_FINDER_PATH)/$(DENSE_SUBGRAPHS) \
 	--graph $(SW_GRAPH) \
 	--output . \
 	--threads %THREADS \
 	--min-snode-size %MIN_SUPER_NODE_SIZE

clean:
	$(RM) $(DENSE_SUBGRAPHS)
	$(MAKE) -C $(IG_GRAPH_CONSTRUCTOR) clean
