---
title: "Gen Statistics"
author: "Andy"
date: "September 20, 2015"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, messages=FALSE, cache=T)
```

```{r}
library("lattice")
library("latticeExtra")
library("parallel")
library("corrplot")
library("plyr")
```

```{r}
z.prop = function(x1,x2,n1,n2){
  numerator = (x1/n1) - (x2/n2)
  p.common = (x1+x2) / (n1+n2)
  denominator = sqrt(p.common * (1-p.common) * (1/n1 + 1/n2))
  z.prop.ris = numerator / denominator
  return(z.prop.ris)
}
```


```{r}
cor.clavage.gen <- function(df, Type.segment, threshold, left.b = 0, right.b = 1) {
  df_length = length(df)
  v.df <- lapply(df, function(x) { droplevels(subset(x, x$Type == Type.segment)) })
  v.df_true <- lapply(v.df, function(x) droplevels(subset(x, x$Clavage)))
  
  #t_full <- lapply(v.df, function(x) { table(x$subject_id)})
  t_full <- lapply(v.df, function(x) { unlist(by(x, x$subject_id, function(y) sum(y$abundance), simplify=FALSE)) })
  #t_full <- t_full[-(length(t_full) - 2)]
  #t_true <- lapply(v.df_true, function(x) table(x$subject_id))
  t_true <- lapply(v.df_true, function(x) { unlist(by(x, x$subject_id, function(y) sum(y$abundance), simplify=FALSE)) })
  #t_true <- t_true[-(length(t_true) - 2)]
  
  #ind <- lapply(t_true, function(x) which(x > threshold))
  #t_full <- mapply(function(x, i) { x[i] }, t_full, ind, SIMPLIFY = FALSE)
  t_true <- lapply(t_true, function(x) { x[x > threshold] })
  t_full <- mapply(function(x, y) { x[names(y)] }, t_full, t_true, SIMPLIFY = FALSE)
  #mapply(function(x, y) { sort(x / y) }, t_true, t_full)
    
  intersectSeveral <- function(...) { Reduce(function(x, y) { intersect(x, y) }, list(...)[[1]]) }
  t_full_intersected <- lapply(t_full, function(x) x[intersectSeveral(lapply(t_true, names))])
  t_true_intersected <- lapply(t_true, function(x) x[intersectSeveral(lapply(t_true, names))])
  #print(t_full_intersected)
  #mapply(function(x, y) sort(x / y), t_true_intersected, t_full_intersected, SIMPLIFY = FALSE)
  
  p_clavage <- mapply(function(x, y) x / y, t_true_intersected, t_full_intersected, SIMPLIFY = FALSE)
  #apply(simplify2array(p_clavage), 1, mean)
  #apply(simplify2array(p_clavage), 1, sd)
  
  s2a_p_clavage <- simplify2array(p_clavage)
  s2a_p_clavage
}

df.processing <- function(df, threshold.perc.identity = 100) {
  df <- mclapply(df, function(x) {x$Clavage <- toupper(x$Clavage); x }, mc.cores = detectCores())
  df <- mclapply(df, function(x) {x$Clavage <- as.logical(x$Clavage); x}, mc.cores = detectCores())
  df <- mclapply(df, function(x) {x$subject_id <- as.factor(x$subject_id); x}, mc.cores = detectCores())
  df <- mclapply(df, function(x) {x$Type <- as.factor(x$Type); x}, mc.cores = detectCores())
  df <- mclapply(df, function(x) subset(x, perc_identity >= threshold.perc.identity), mc.cores = detectCores())
  df
}

cor.clavage.gen.all <- function(df, threshold = 1000) {
  list("V"       = cor.clavage.gen(df, "V", threshold = threshold),
       "D left"  = cor.clavage.gen(df, "D left", left.b = 0.5, threshold = threshold),
       "D right" = cor.clavage.gen(df, "D right", left.b = 0.5, threshold = threshold),
       "J"       = cor.clavage.gen(df, "J", left.b = 0.8, threshold = threshold)
  )
}

pairs.plots <- function(barcodes) {
  print(pairs(barcodes[["V"]], xlim = c(0, 1), ylim = c(0, 1), main = "V"))
  print(pairs(barcodes[["D left"]], xlim = c(0.5, 1), ylim = c(0.5, 1), main = "D left"))
  print(pairs(barcodes[["D right"]], xlim = c(0.5, 1), ylim = c(0.5, 1), main = "D right"))
  print(pairs(barcodes[["J"]], xlim = c(0.8, 1), ylim = c(0.8, 1), main = "J"))
}

permutation.test <- function(a, b, df.length) {
  tmp <- matrix( c(a, sample(b)), nrow = length(a), ncol = df.length )
  #print(tmp)
  cor(tmp[,1], tmp[,2])
}

z.test <- function(df, Type.segment, threshold, left.b = 0, right.b = 1) {
  df_length = length(df)
  stopifnot(length(df) == 2)
  v.df <- lapply(df, function(x) { droplevels(subset(x, x$Type == Type.segment)) })
  v.df_true <- lapply(v.df, function(x) droplevels(subset(x, x$Clavage)))
  
  t_full <- lapply(v.df, function(x) { unlist(by(x, x$subject_id, function(y) sum(y$abundance), simplify=FALSE)) })
  t_true <- lapply(v.df_true, function(x) { unlist(by(x, x$subject_id, function(y) sum(y$abundance), simplify=FALSE)) })
  t_true <- lapply(t_true, function(x) { x[x > threshold] })
  t_full <- mapply(function(x, y) { x[names(y)] }, t_full, t_true, SIMPLIFY = FALSE)
    
  intersectSeveral <- function(...) { Reduce(function(x, y) { intersect(x, y) }, list(...)[[1]]) }
  t_full_intersected <- lapply(t_full, function(x) x[intersectSeveral(lapply(t_true, names))])
  t_true_intersected <- lapply(t_true, function(x) x[intersectSeveral(lapply(t_true, names))])
  
  mapply(z.prop, t_true_intersected[[1]], t_true_intersected[[2]], t_full_intersected[[1]], t_full_intersected[[2]])
}
```

# AGE
## 9 AGE

```{r}
df <- lapply((1:9), function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
df <- df.processing(df)
#df <- append(df, list(read.csv("../1_SAM13306969.csv", header = T, sep = "\t")))#, read.csv("2_SAM13306970.csv", header = T, sep = "\t")))

age.barcodes <- cor.clavage.gen.all(df)
age.barcodes
pairs.plots(age.barcodes)

corr <- lapply(age.barcodes, cor)
l_ply(corr, corrplot, method="number")

corr <- lapply(age.barcodes, cor, method = "spearman")
l_ply(corr, corrplot, method="number")
```

```{r}
df <- lapply((1:9), function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
#df <- append(df, list(read.csv("../1_SAM13306969.csv", header = T, sep = "\t")))#, read.csv("2_SAM13306970.csv", header = T, sep = "\t")))
df <- list(Reduce(function(...) merge(..., all=T), df[1:4]), Reduce(function(...) merge(..., all=T), df[5:9]))
df <- df.processing(df)

age.barcodes.reduced.eq  <- cor.clavage.gen.all(df)
age.barcodes.reduced.eq

pairs.plots(age.barcodes.reduced.eq)

p1 <- xyplot(age.barcodes.reduced.eq[['V']][,1] ~ age.barcodes.reduced.eq[['V']][,2], xlim = c(0, 1), ylim = c(0, 1), col = "blue", 
             main = list(label = "V genes: probability of cleavage", fontsize = 25), 
             xlab = list(label = "Age datasets 1--4", fontsize = 25), 
             ylab = list(label = "Age datasets 5--9", fontsize = 25), cex = 1.2, pch = 19, par.strip.text = list(cex.title = 5))
p2 <- xyplot(0:1~0:1, col = "black", type = "l")

p1 + as.layer(p2)


p1 <- xyplot(age.barcodes.reduced.eq[['J']][,1] ~ age.barcodes.reduced.eq[['V']][,2], xlim = c(0.7, 1), ylim = c(0.7, 1), col = "blue", 
             main = list(label = "J genes: probability of cleavage", fontsize = 25), 
             xlab = list(label = "Age datasets 1--4", fontsize = 25), 
             ylab = list(label = "Age datasets 5--9", fontsize = 25), cex = 1.2, pch = 19, par.strip.text = list(cex.title = 5))
p2 <- xyplot(0:1~0:1, col = "black", type = "l")

p1 + as.layer(p2)

corr <- lapply(age.barcodes.reduced.eq, cor)
l_ply(corr, corrplot, method="number")

corr <- lapply(age.barcodes.reduced.eq, cor, method = "spearman")
l_ply(corr, corrplot, method="number")
```

```{r}
N <- 1000
out <- lapply(age.barcodes.reduced.eq, function(x) {
      c(cor(x[,1], x[,2]), replicate(N, permutation.test(x[,1], x[,2], length(df)))) 
    }
  )
lapply(out, function(x) {
    #print(hist(x))
    print(histogram(x, col = "aquamarine",
      main = list(label = "Permutation test: significance of the correlation", fontsize = 25), 
      xlab = list(label = "Correlation", fontsize = 25), 
      ylab = list(label = "Frequence", fontsize = 25), cex = 1.2, pch = 19, par.strip.text = list(cex.title = 5),
      panel = function(x, ...) {
         panel.histogram(x, ...)
         panel.abline(v = x[1], col = 'red')
      }))
    #print(abline(v=x[1], col='red'))
  }
)
```

```{r}
zt <- z.test(df = df, Type.segment = "V", threshold = 1000)
shapiro.test(zt)
```

```{r}
#a <- by(df[[1]], df[[1]]$N, function(x) as.vector(x$subject_id[c(1, length(x$subject_id))]))
#b <- matrix(unlist(a), nrow = 2, ncol = length(unlist(a)) /2)
#table(b[1,], b[2,])
```


# SAM

```{r}
#df <- lapply((1:9)[-5], function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
df <- list(read.csv("../1_SAM13306969.csv", header = T, sep = "\t"), read.csv("../2_SAM13306970.csv", header = T, sep = "\t"))
#df <- list(Reduce(function(...) merge(..., all=T), df[1:4]), Reduce(function(...) merge(..., all=T), df[5:10]))
df <- df.processing(df, threshold.perc.identity = 95)

sam.dataset  <- cor.clavage.gen.all(df)
sam.dataset

pairs.plots(sam.dataset)

corr <- lapply(sam.dataset, cor)
corr
l_ply(corr, corrplot, method="number")

corr <- lapply(sam.dataset, cor, method = "spearman")
corr
l_ply(corr, corrplot, method="number")
```


```{r}
#df <- lapply((1:9)[-5], function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
df <- list(read.csv("../7_SAM15574987.csv", header = T, sep = "\t"), read.csv("../8_SAM15574988.csv", header = T, sep = "\t"))
#df <- list(Reduce(function(...) merge(..., all=T), df[1:4]), Reduce(function(...) merge(..., all=T), df[5:10]))
df <- df.processing(df, threshold.perc.identity = 95)

sam.dataset  <- cor.clavage.gen.all(df)
sam.dataset

pairs.plots(sam.dataset)

corr <- lapply(sam.dataset, cor)
corr
l_ply(corr, corrplot, method="number")

corr <- lapply(sam.dataset, cor, method = "spearman")
corr
l_ply(corr, corrplot, method="number")
```

```{r}
#df <- lapply((1:9)[-5], function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
df <- list(read.csv("../1_SAM13306969.csv", header = T, sep = "\t"), read.csv("../7_SAM15574987.csv", header = T, sep = "\t"))
#df <- list(Reduce(function(...) merge(..., all=T), df[1:4]), Reduce(function(...) merge(..., all=T), df[5:10]))
df <- df.processing(df, threshold.perc.identity = 98)

sam.dataset  <- cor.clavage.gen.all(df)
sam.dataset

pairs.plots(sam.dataset)

corr <- lapply(sam.dataset, cor)
corr
l_ply(corr, corrplot, method="number")

corr <- lapply(sam.dataset, cor, method = "spearman")
corr
l_ply(corr, corrplot, method="number")
```


```{r}
#df <- lapply((1:9)[-5], function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
df <- list(read.csv("../1_SAM13306969.csv", header = T, sep = "\t"), read.csv("../8_SAM15574988.csv", header = T, sep = "\t"))
#df <- list(Reduce(function(...) merge(..., all=T), df[1:4]), Reduce(function(...) merge(..., all=T), df[5:10]))
df <- df.processing(df, threshold.perc.identity = 98)

sam.dataset  <- cor.clavage.gen.all(df)
sam.dataset

pairs.plots(sam.dataset)

corr <- lapply(sam.dataset, cor)
corr
l_ply(corr, corrplot, method="number")

corr <- lapply(sam.dataset, cor, method = "spearman")
corr
l_ply(corr, corrplot, method="number")
```

```{r}
#df <- lapply((1:9)[-5], function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
df <- list(read.csv("../2_SAM13306970.csv", header = T, sep = "\t"), read.csv("../7_SAM15574987.csv", header = T, sep = "\t"))
#df <- list(Reduce(function(...) merge(..., all=T), df[1:4]), Reduce(function(...) merge(..., all=T), df[5:10]))
df <- df.processing(df, threshold.perc.identity = 98)

sam.dataset  <- cor.clavage.gen.all(df)
sam.dataset

pairs.plots(sam.dataset)

corr <- lapply(sam.dataset, cor)
corr
l_ply(corr, corrplot, method="number")

corr <- lapply(sam.dataset, cor, method = "spearman")
corr
l_ply(corr, corrplot, method="number")
```


```{r}
#df <- lapply((1:9)[-5], function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
df <- list(read.csv("../2_SAM13306970.csv", header = T, sep = "\t"), read.csv("../8_SAM15574988.csv", header = T, sep = "\t"))
#df <- list(Reduce(function(...) merge(..., all=T), df[1:4]), Reduce(function(...) merge(..., all=T), df[5:10]))
df <- df.processing(df, threshold.perc.identity = 98)

sam.dataset  <- cor.clavage.gen.all(df)
sam.dataset

pairs.plots(sam.dataset)

corr <- lapply(sam.dataset, cor)
corr
l_ply(corr, corrplot, method="number")

corr <- lapply(sam.dataset, cor, method = "spearman")
corr
l_ply(corr, corrplot, method="number")
```

```{r}
#df <- lapply((1:9)[-5], function(i) read.csv(paste("../", i, ".csv", sep = ""), header = T, sep = "\t"))
df <- list(read.csv("../SAMEA2240927_ERX319432.csv", header = T, sep = "\t"), 
           read.csv("../SAMEA2240927_ERX319436.csv", header = T, sep = "\t"),
           read.csv("../SAMEA2240927_ERX319437.csv", header = T, sep = "\t")
           )
#df <- list(Reduce(function(...) merge(..., all=T), df[1:4]), Reduce(function(...) merge(..., all=T), df[5:10]))
df <- df.processing(df, threshold.perc.identity = 0)

SAMEA  <- cor.clavage.gen.all(df)
SAMEA

pairs.plots(SAMEA)

corr <- lapply(SAMEA, cor)
corr
l_ply(corr, corrplot, method="number")

corr <- lapply(SAMEA, cor, method = "spearman")
corr
l_ply(corr, corrplot, method="number")
```

```{r}
df <- list(read.csv("../BSSE_QGF_20433_naive.csv", header = T, sep = "\t"))
df <- df.processing(df, threshold.perc.identity = 0)

BSSE  <- cor.clavage.gen.all(df)
BSSE
```

